# Generated by Django 3.1.3 on 2020-12-17 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Adı')),
                ('lastname', models.CharField(max_length=50, verbose_name='Soyadı')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('placeOfBirth', models.TextField(blank=True, null=True, verbose_name='Doğum Yeri')),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
            },
        ),
        migrations.CreateModel(
            name='CapType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kapak Türü')),
            ],
            options={
                'verbose_name': 'Kapat Türü',
                'verbose_name_plural': 'Kapak Türleri',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dil Adı')),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yayınevi Adı')),
            ],
            options={
                'verbose_name': 'Yayınevi',
                'verbose_name_plural': 'Yayınevleri',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adı')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyadı')),
                ('dateOfBirth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('placeOfBirth', models.TextField(blank=True, null=True, verbose_name='Doğum Yeri')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Yaşı')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='Okuma Hızı(Günlük)')),
                ('profilPhoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Fotoğrafı')),
                ('language', models.ManyToManyField(blank=True, null=True, to='Home.Language', verbose_name='Dil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ('firstname', 'lastname', 'age', 'speed'),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kitap Adı')),
                ('pageCount', models.IntegerField(verbose_name='Sayfa Sayısı')),
                ('point', models.CharField(max_length=10, verbose_name='Puan')),
                ('coverPhoto', models.ImageField(upload_to='', verbose_name='Kapak Fotoğrafı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.author', verbose_name='Yazar')),
                ('bookCategory', models.ManyToManyField(to='Home.Category', verbose_name='Kategori')),
                ('capType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.captype', verbose_name='Kapak Türü')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.language', verbose_name='Dil')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.publisher', verbose_name='Yayınevi')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ('name', 'author', 'publisher'),
            },
        ),
    ]
