# Generated by Django 3.1.3 on 2020-12-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('firstname', 'lastname'), 'verbose_name': 'Yazar', 'verbose_name_plural': 'Yazarlar'},
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(default=None, max_length=50, verbose_name='Adı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='lastname',
            field=models.CharField(default=None, max_length=50, verbose_name='Soyadı'),
            preserve_default=False,
        ),
    ]
