# Generated by Django 3.1.3 on 2020-12-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201218_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
