# Generated by Django 3.1.3 on 2020-12-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20201219_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='Home.Book', verbose_name='Kitaplar'),
        ),
    ]
