# Generated by Django 3.1.3 on 2020-12-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_users_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reading_book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_reading_book', to='Home.book', verbose_name='Şuan Okuduğu Kitap'),
        ),
    ]
