# Generated by Django 3.1.3 on 2020-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_users_reading_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reading_book_addition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Okuduğu Kitabı Ekleme Tarihi'),
        ),
    ]
